version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      ollama:
        condition: service_started
      auth-service:
        condition: service_healthy
  chatbot-service:
    build:
      context: ./backend
    container_name: chatbot-service
    ports:
      - "8001:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app/src
    depends_on:
      qdrant:
        condition: service_started
      ollama:
        condition: service_started
      auth-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  auth-service:
    image: quay.io/keycloak/keycloak:latest
    container_name: auth-service
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command: ["start-dev"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 15s
      timeout: 10s
      retries: 20

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333"  # gRPC
      - "6334:6334"  # HTTP
    volumes:
      - qdrant_data:/qdrant/storage
    # Not adding a healthcheck for qdrant for now to keep it simple,
    # as its default / path might not be suitable for a basic curl check.

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data: {}
  qdrant_data: {}