version: '3.8'

networks:
  dws-network:
    driver: bridge

services:
  chatbot-service:
    build:
      context: ./backend
    container_name: chatbot-service
    ports:
      - "8001:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app/src
    depends_on:
      qdrant:
        condition: service_started
      ollama:
        condition: service_started
      auth-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - dws-network

  auth-service:
    image: quay.io/keycloak/keycloak:latest
    container_name: auth-service
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: ["start-dev", "--import-realm"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 15s
      timeout: 10s
      retries: 20
    networks:
      - dws-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333"  # gRPC
      - "6334:6334"  # HTTP
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - dws-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - dws-network

volumes:
  ollama_data: {}
  qdrant_data: {}