version: '3.8'
services:
  chatbot-service:
    build:
      context: ./backend
    container_name: chatbot-service
    ports:
      - "8001:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app/src
    depends_on:
      qdrant:
        condition: service_started # Or service_healthy if qdrant had a reliable healthcheck
      ollama:
        condition: service_started # Assuming ollama doesn't have a specific healthcheck here
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333"  # gRPC
      - "6334:6334"  # HTTP
    volumes:
      - qdrant_data:/qdrant/storage
    # Not adding a healthcheck for qdrant for now to keep it simple,
    # as its default / path might not be suitable for a basic curl check.

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data: {}
  qdrant_data: {}